heat_template_version: 2013-05-23

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)

  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: performance1-8

  key_name:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: default

  os_ansible_git_repo:
    type: string
    label: RPC git repo
    description: URL of RPC git repo to clone
    default: https://github.com/stackforge/os-ansible-deployment

  os_ansible_git_version:
    type: string
    label: RPC version
    description: RPC version to install (master, juno, stable, 9.0.5, 10.1.1, etc.)
    default: master

  heat_git_repo:
    type: string
    label: Heat git repo
    description: URL of Heat git repo to clone
    default: https://github.com/rcbops/rpc-heat

  heat_git_version:
    type: string
    label: Heat version
    description: Heat version to install
    default: master

  cluster_prefix:
    type: string
    label: Cluster prefix
    description: Prefix to use when building cluster
    default: heat
    constraints:
      # The recommended hostname length should be less than 20 chars, we tack
      # on -nodeX which adds up to another 5 chars, hence max being 14.
      - length: { min: 1, max: 14 }

  deploy_infrastructure:
    type: string
    label: Deploy infrastructure playbooks
    description: Deploy infrastructure playbooks
    default: yes

  deploy_logging:
    type: string
    label: Deploy logging solution
    description: Deploy logging solution
    default: yes

  deploy_openstack:
    type: string
    label: Deploy openstack playbooks
    description: Deploy openstack playbooks
    default: yes

  deploy_tempest:
    type: string
    label: Deploy tempest
    description: Deploy tempest
    default: no

  deploy_swift:
    type: string
    label: Deploy swift
    description: Deploy swift
    default: yes

  deploy_monitoring:
    type: string
    label: Deploy monitoring solution
    description: Deploy monitoring solution (this will only work on Rackspace Cloud Servers instances)
    default: yes

  run_ansible:
    type: boolean
    label: Run ansible
    description: If true ansible will be run as part of the stack-create
    default: true

  rackspace_cloud_api_key:
    type: string
    label: Rackspace Cloud API Key
    description: Rackspace Cloud API Key
    default: SomeAPIKey
    hidden: True

  rackspace_cloud_auth_url:
    type: string
    label: Rackspace Cloud Auth URL
    description: Rackspace Cloud Auth URL
    default: https://identity.api.rackspacecloud.com/v2.0
    hidden: True

  rackspace_cloud_password:
    type: string
    label: Rackspace Cloud Password
    description: Rackspace Cloud Password
    default: SomeUsersPassword
    hidden: True

  rackspace_cloud_tenant_id:
    type: string
    label: Rackspace Cloud Tenant ID
    description: Rackspace Cloud Tenant ID
    default: SomeTenantID
    hidden: True

  rackspace_cloud_username:
    type: string
    label: Rackspace Cloud Username
    description: Rackspace Cloud Username
    default: SomeUserName
    hidden: True

  glance_default_store:
    type: string
    label: Glance Default Store
    description: The storage backend to configure glance with
    default: swift
    constraints:
      - allowed_values: [ swift, file ]

  glance_swift_store_region:
    type: string
    label: Glance Swift Store Region
    description: The swift region to store glance images in
    default: LON
    constraints:
      - allowed_values: [ DFW, HKG, IAD, LON, ORD, SYD ]

  gerrit_refspec:
    type: string
    label: Git reference for the patch to test

  run_tempest:
    type: boolean
    label: Run tempest after deploying
    default: false

  tempest_script_parameters:
    type: string
    label: parameters to pass to pass to run-tempest which calls openstack_tempest_gate
    default: nightly_heat_multinode

resources:
  controller1_wait:
    type: "OS::Heat::SwiftSignal"
    properties:
      handle: { get_resource: controller1_wait_handle }
      count: 1
      timeout: 7200
  controller1_wait_handle:
    type: "OS::Heat::SwiftSignalHandle"

  controller2_wait:
    type: "OS::Heat::SwiftSignal"
    properties:
      handle: { get_resource: controller2_wait_handle }
      count: 1
      timeout: 900
  controller2_wait_handle:
    type: "OS::Heat::SwiftSignalHandle"

  controller3_wait:
    type: "OS::Heat::SwiftSignal"
    properties:
      handle: { get_resource: controller3_wait_handle }
      count: 1
      timeout: 900
  controller3_wait_handle:
    type: "OS::Heat::SwiftSignalHandle"

  compute1_wait:
    type: "OS::Heat::SwiftSignal"
    properties:
      handle: { get_resource: compute1_wait_handle }
      count: 1
      timeout: 900
  compute1_wait_handle:
    type: "OS::Heat::SwiftSignalHandle"

  compute2_wait:
    type: "OS::Heat::SwiftSignal"
    properties:
      handle: { get_resource: compute2_wait_handle }
      count: 1
      timeout: 900
  compute2_wait_handle:
    type: "OS::Heat::SwiftSignalHandle"

  ansible_keypair:
    type: "OS::Nova::KeyPair"
    properties:
      name:
        str_replace:
          template: "%%CLUSTER_PREFIX%%-key"
          params:
            "%%CLUSTER_PREFIX%%": { get_param: cluster_prefix }
      save_private_key: true

  heat_mgmt_vxlan:
    type: Rackspace::Cloud::Network
    properties:
      cidr: 172.29.236.0/22
      label: heat_mgmt_vxlan

  heat_tunnel:
    type: Rackspace::Cloud::Network
    properties:
      cidr: 172.29.240.0/22
      label: heat_tunnel

  heat_storage:
    type: Rackspace::Cloud::Network
    properties:
      cidr: 172.29.228.0/22
      label: heat_storage

  controller1:
    type: "OS::Nova::Server"
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      name:
        str_replace:
          template: "%%CLUSTER_PREFIX%%-node1"
          params:
            "%%CLUSTER_PREFIX%%": { get_param: cluster_prefix }
      networks:
        - uuid: 00000000-0000-0000-0000-000000000000
        - uuid: 11111111-1111-1111-1111-111111111111
        - uuid: { get_resource: heat_mgmt_vxlan }
        - uuid: { get_resource: heat_tunnel }
        - uuid: { get_resource: heat_storage }
      config_drive: True
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: config_controller_primary.sh }
          params:
            "%%ID%%": "1"
            "%%EXTERNAL_VIP_IP%%": { get_attr: [controller3, accessIPv4] }
            "%%PRIVATE_KEY%%": { get_attr: [ansible_keypair, private_key] }
            "%%PUBLIC_KEY%%": { get_attr: [ansible_keypair, public_key] }
            "%%CLUSTER_PREFIX%%": { get_param: cluster_prefix }
            "%%DEPLOY_INFRASTRUCTURE%%": { get_param: deploy_infrastructure }
            "%%DEPLOY_LOGGING%%": { get_param: deploy_logging }
            "%%DEPLOY_OPENSTACK%%": { get_param: deploy_openstack }
            "%%DEPLOY_TEMPEST%%": { get_param: deploy_tempest }
            "%%RUN_TEMPEST%%": { get_param: run_tempest }
            "%%TEMPEST_SCRIPT_PARAMETERS%%": { get_param: tempest_script_parameters }
            "%%DEPLOY_SWIFT%%": { get_param: deploy_swift }
            "%%DEPLOY_MONITORING%%": { get_param: deploy_monitoring }
            "%%OS_ANSIBLE_GIT_REPO%%": { get_param: os_ansible_git_repo }
            "%%OS_ANSIBLE_GIT_VERSION%%": { get_param: os_ansible_git_version }
            "%%HEAT_GIT_REPO%%": { get_param: heat_git_repo }
            "%%HEAT_GIT_VERSION%%": { get_param: heat_git_version }
            "%%RACKSPACE_CLOUD_API_KEY%%": { get_param: rackspace_cloud_api_key }
            "%%RACKSPACE_CLOUD_AUTH_URL%%": { get_param: rackspace_cloud_auth_url }
            "%%RACKSPACE_CLOUD_PASSWORD%%": { get_param: rackspace_cloud_password }
            "%%RACKSPACE_CLOUD_TENANT_ID%%": { get_param: rackspace_cloud_tenant_id }
            "%%RACKSPACE_CLOUD_USERNAME%%": { get_param: rackspace_cloud_username }
            "%%GLANCE_DEFAULT_STORE%%": { get_param: glance_default_store }
            "%%GLANCE_SWIFT_STORE_REGION%%": { get_param: glance_swift_store_region }
            "%%RUN_ANSIBLE%%": { get_param: run_ansible }
            "%%CURL_CLI%%": { get_attr: ['controller1_wait_handle', 'curl_cli'] }
            "%%GERRIT_REFSPEC%%": { get_param: gerrit_refspec }

  controller2:
    type: "OS::Nova::Server"
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      name:
        str_replace:
          template: "%%CLUSTER_PREFIX%%-node2"
          params:
            "%%CLUSTER_PREFIX%%": { get_param: cluster_prefix }
      networks:
        - uuid: 00000000-0000-0000-0000-000000000000
        - uuid: 11111111-1111-1111-1111-111111111111
        - uuid: { get_resource: heat_mgmt_vxlan }
        - uuid: { get_resource: heat_tunnel }
        - uuid: { get_resource: heat_storage }
      config_drive: True
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: config_controller_other.sh }
          params:
            "%%ID%%": "2"
            "%%PUBLIC_KEY%%": { get_attr: [ansible_keypair, public_key] }
            "%%CLUSTER_PREFIX%%": { get_param: cluster_prefix }
            "%%DEPLOY_SWIFT%%": { get_param: deploy_swift }
            "%%CURL_CLI%%": { get_attr: ['controller2_wait_handle', 'curl_cli'] }

  controller3:
    type: "OS::Nova::Server"
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      name:
        str_replace:
          template: "%%CLUSTER_PREFIX%%-node3"
          params:
            "%%CLUSTER_PREFIX%%": { get_param: cluster_prefix }
      networks:
        - uuid: 00000000-0000-0000-0000-000000000000
        - uuid: 11111111-1111-1111-1111-111111111111
        - uuid: { get_resource: heat_mgmt_vxlan }
        - uuid: { get_resource: heat_tunnel }
        - uuid: { get_resource: heat_storage }
      config_drive: True
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: config_controller_other.sh }
          params:
            "%%ID%%": "3"
            "%%PUBLIC_KEY%%": { get_attr: [ansible_keypair, public_key] }
            "%%CLUSTER_PREFIX%%": { get_param: cluster_prefix }
            "%%DEPLOY_SWIFT%%": { get_param: deploy_swift }
            "%%CURL_CLI%%": { get_attr: ['controller3_wait_handle', 'curl_cli'] }

  compute1:
    type: "OS::Nova::Server"
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      name:
        str_replace:
          template: "%%CLUSTER_PREFIX%%-node4"
          params:
            "%%CLUSTER_PREFIX%%": { get_param: cluster_prefix }
      networks:
        - uuid: 00000000-0000-0000-0000-000000000000
        - uuid: 11111111-1111-1111-1111-111111111111
        - uuid: { get_resource: heat_mgmt_vxlan }
        - uuid: { get_resource: heat_tunnel }
        - uuid: { get_resource: heat_storage }
      config_drive: True
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: config_compute_all.sh }
          params:
            "%%ID%%": "4"
            "%%PUBLIC_KEY%%": { get_attr: [ansible_keypair, public_key] }
            "%%CLUSTER_PREFIX%%": { get_param: cluster_prefix }
            "%%CURL_CLI%%": { get_attr: ['compute1_wait_handle', 'curl_cli'] }

  compute2:
    type: "OS::Nova::Server"
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      name:
        str_replace:
          template: "%%CLUSTER_PREFIX%%-node5"
          params:
            "%%CLUSTER_PREFIX%%": { get_param: cluster_prefix }
      networks:
        - uuid: 00000000-0000-0000-0000-000000000000
        - uuid: 11111111-1111-1111-1111-111111111111
        - uuid: { get_resource: heat_mgmt_vxlan }
        - uuid: { get_resource: heat_tunnel }
        - uuid: { get_resource: heat_storage }
      config_drive: True
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: config_compute_all.sh }
          params:
            "%%ID%%": "5"
            "%%PUBLIC_KEY%%": { get_attr: [ansible_keypair, public_key] }
            "%%CLUSTER_PREFIX%%": { get_param: cluster_prefix }
            "%%CURL_CLI%%": { get_attr: ['compute2_wait_handle', 'curl_cli'] }

outputs:
  controller1_ip:
    description: The IP address of controller1
    value: { get_attr: [controller1, accessIPv4] }
  controller2_ip:
    description: The IP address of controller2
    value: { get_attr: [controller2, accessIPv4] }
  controller3_ip:
    description: The IP address of controller3
    value: { get_attr: [controller3, accessIPv4] }
  compute1_ip:
    description: The IP address of compute1
    value: { get_attr: [compute1, accessIPv4] }
  compute2_ip:
    description: The IP address of compute2
    value: { get_attr: [compute2, accessIPv4] }
